const words = [
  { en: "Mayhem", ru: "хаос, беспорядок", example: "There was total mayhem in the streets." },
  { en: "Front-row seats", ru: "места в первом ряду", example: "We got front-row seats at the concert." },
  { en: "Destruction", ru: "разрушение", example: "The storm caused massive destruction." },
  { en: "Saying", ru: "пословица, поговорка", example: "As the saying goes, time heals all wounds." },
  { en: "I wonder how", ru: "Интересно, как", example: "I wonder how they did it." },
  { en: "Demolition", ru: "снос, разбор", example: "The demolition of the old building is scheduled for Monday." },
  { en: "Vowels", ru: "гласные", example: "A, E, I, O, U are vowels." },
  { en: "Say a few words", ru: "сказать пару слов", example: "Would you like to say a few words at the ceremony?" },
  { en: "To mark the occasion", ru: "отметить событие", example: "We opened a bottle of wine to mark the occasion." },
  { en: "People are asking me if I know something", ru: "Люди спрашивают меня, знаю ли я что-то", example: "People are asking me if I know something about the accident." },
  { en: "Hidden", ru: "скрытый, спрятанный", example: "There was a hidden message in the letter." },
  { en: "Testicular", ru: "яичковый", example: "Testicular cancer is treatable if caught early." },
  { en: "Support", ru: "поддержка", example: "Thank you for your support." },
  { en: "Realize", ru: "осознавать, понимать", example: "I didn't realize how late it was." },
  { en: "Have something to do with", ru: "иметь отношение к", example: "Does this have something to do with the project?" },
  { en: "comb", ru: "расчёска", example: "She used a comb to fix her hair." },
  { en: "The tomb", ru: "могила, гробница", example: "They discovered an ancient tomb in Egypt." },
  { en: "Accomplished", ru: "достигнутый,successful", example: "She is an accomplished pianist." },
  { en: "cinder", ru: " уголь, зола", example: "The cinder from the fire was still warm." },
  { en: "Smoldering rubble", ru: " тлеющие обломки", example: "The building was reduced to smoldering rubble." },
  { en: "Smolder", ru: "тлеть, дымиться", example: "The fire continued to smolder for hours." },
  { en: "Reduce", ru: "уменьшать, снижать", example: "We need to reduce our expenses." },
  { en: "Wrap", ru: "заворачивать, обёртка", example: "Help me wrap this gift." },
  { en: "Influence", ru: "влияние", example: "Parents have a big influence on their children." },
  { en: "Impact", ru: "влияние, удар", example: "The impact of the new policy was significant." },
  { en: "Enormous", ru: "огромный", example: "The elephant was enormous." },
  { en: "Wound", ru: "рана", example: "The wound on his arm was deep." },
  { en: "Drain the fluid", ru: "слить жидкость", example: "The doctor had to drain the fluid from his knee." },
  { en: "Upped", ru: "повысил, увеличил", example: "They upped the price by 10 percent." },
  { en: "Oestrogen", ru: "эстроген", example: "Oestrogen levels change during the menstrual cycle." },
  { en: "Testosterone", ru: "тестостерон", example: "Testosterone is a male hormone." },
  { en: "Remove", ru: "удалять, убирать", example: "Please remove your shoes before entering." },
  { en: "Slopy", ru: "кривой, неровный", example: "The handwriting was slopy and hard to read." },
  { en: "Moose", ru: "лось", example: "We saw a moose in the forest." },
  { en: "Slobber", ru: "слюни, пускать слюни", example: "The dog slobbered all over the couch." },
  { en: "fold", ru: "складывать, сгибать", example: "Fold the paper in half." },
  { en: "Ultimate", ru: "конечный, лучший", example: "This is the ultimate guide to cooking." },
  { en: "Return to the fold", ru: "вернуться в стаю, вернуться в круг", example: "He finally returned to the fold after years away." },
  { en: "Crook", ru: "мошенник, изгиб", example: "The crook was arrested by the police." },
  { en: "Draft", ru: "черновик, сквозняк", example: "I need to write a draft of the report." },
  { en: "Feel a draft", ru: "чувствовать сквозняк", example: "I feel a draft from that window." },
  { en: "Cowl", ru: "капюшон, колпак", example: "He pulled his cowl over his head." },
  { en: "Chimp", ru: "шимпанзе", example: "The chimp was eating a banana." },
  { en: "Rumor", ru: "слух", example: "There's a rumor that the company is closing." },
  { en: "Gem", ru: "драгоценный камень", example: "The ring had a beautiful gem." },
  { en: "To attend to", ru: "присматривать за, обрабатывать", example: "I need to attend to some urgent matters." },
  { en: "Stuffing", ru: "начинка, набивка", example: "The turkey was filled with delicious stuffing." },
  { en: "Gravy", ru: "соус, подливка", example: "Pour the gravy over the mashed potatoes." },
  { en: "Monk", ru: "монах", example: "The monk lived alone in the monastery." },
  { en: "Grief", ru: "горе, печаль", example: "She was overcome with grief after the loss." },
  { en: "To suffer", ru: "страдать", example: "He suffered from a severe headache." },
  { en: "Torture", ru: "пытка, мука", example: "Waiting for the results was torture." },
  { en: "Thief", ru: "вор", example: "The thief stole her wallet." },
  { en: "Sneaky pickpocket", ru: "хитрый карманник", example: "A sneaky pickpocket stole his phone on the bus." },
  { en: "Sneaky", ru: "хитрый, скрытный", example: "That was a sneaky trick." },
  { en: "Keep away from me", ru: "держись от меня подальше", example: "Keep away from me, I'm contagious!" },
  { en: "Clumsy", ru: "неуклюжий", example: "He's so clumsy, he dropped the vase." },
  { en: "Beggar", ru: "нищий, попрошайка", example: "The beggar asked for some money." },
  { en: "Beg", ru: "просить, выпрашивать", example: "I beg your pardon?" },
  { en: "To be up to something", ru: "что-то замышлять", example: "I think you're up to something." },
  { en: "Junkfood", ru: "фастфуд", example: "Too much junkfood is bad for your health." },
  { en: "Junk", ru: "мусор, хлам", example: "We need to clear out all this junk." },
  { en: "Bargain", ru: "сделка, выгодная покупка", example: "This shirt was a real bargain." },
  { en: "Priceless", ru: "бесценный", example: "The look on her face was priceless." },
  { en: "Worthless", ru: "бесполезный, ничего не стоящий", example: "That old phone is worthless now." },
  { en: "Worth", ru: "стоимость, ценность", example: "What is this painting worth?" },
  { en: "Riddle", ru: "загадка", example: "Can you solve this riddle?" },
  { en: "Stir", ru: "помешивать, взбаламутить", example: "Stir the soup before serving." },
  { en: "Terrain", ru: "местность, рельеф", example: "The terrain was rough and rocky." },
  { en: "Busload", ru: "автобус (загрузка)", example: "A busload of tourists arrived at the museum." },
  { en: "Molest", ru: "преследовать, домогаться", example: "He was arrested for molesting a minor." },
  { en: "Spit", ru: "плевать", example: "It's rude to spit on the street." },
  { en: "To gag", ru: "затыкать рот; давиться", example: "The smoke made me gag." },
  { en: "YouTube helped to figure out", ru: "YouTube помог разобраться", example: "YouTube helped to figure out how to fix the engine." },
  { en: "Shore", ru: "берег", example: "We walked along the shore." },
  { en: "Shoot", ru: "стрелять; снимать", example: "Don't shoot! I surrender." },
  { en: "Shot", ru: "выстрел; кадр", example: "He fired one shot." },
  { en: "Plump", ru: "пухлый", example: "The baby has plump cheeks." },
  { en: "Chubby", ru: "полненький", example: "She is a chubby little girl." },
  { en: "Although", ru: "хотя", example: "Although it was cold, we went out." },
  { en: "Gutting fish", ru: "потрошение рыбы", example: "Gutting fish is not a pleasant job." },
  { en: "Mermaid", ru: "русалка", example: "The mermaid sang a beautiful song." },
  { en: "Protect", ru: "защищать", example: "This cream will protect your skin." },
  { en: "Dedicate", ru: "посвящать", example: "I dedicate this song to my mother." },
  { en: "Dedicated", ru: "преданный; посвящённый", example: "He is a dedicated teacher." },
  { en: "Range hood", ru: "вытяжка (кухонная)", example: "Turn on the range hood when cooking." },
  { en: "Poor", ru: "бедный; плохой", example: "They live in a poor neighborhood." },
  { en: "Pour", ru: "наливать", example: "Could you pour me some water?" },
  { en: "Roam", ru: "бродить", example: "They roam around the city at night." },
  { en: "Creature", ru: "существо", example: "The forest is full of mysterious creatures." },
  { en: "Bow", ru: "кланяться; лук; бант", example: "The performer took a bow." },
  { en: "Chew", ru: "жевать", example: "You should chew your food well." },
  { en: "Prisoner", ru: "заключённый", example: "The prisoner escaped from jail." },
  { en: "Prison", ru: "тюрьма", example: "He spent five years in prison." },
  { en: "Stainless", ru: "нержавеющий; без пятен", example: "Stainless steel is very durable." },
  { en: "Please remain seated until the show is over", ru: "Пожалуйста, оставайтесь на местах до окончания представления", example: "Please remain seated until the show is over." },
  { en: "Atop", ru: "наверху (на вершине)", example: "The flag stands atop the mountain." },
  { en: "It's not a thing to be playing with", ru: "Это не то, с чем стоит играть", example: "Fire is not a thing to be playing with." },
  { en: "It's not I think to be playing with", ru: "Я думаю, это не то, с чем стоит играть (разг.)", example: "It's not I think to be playing with — it's dangerous." },
  { en: "To cast a spell", ru: "наложить заклинание", example: "The witch cast a spell on the prince." },
  { en: "Spell", ru: "заклинание; писать по буквам", example: "Can you spell your name, please?" },
  { en: "Watch carefully", ru: "смотри внимательно", example: "Watch carefully — I'll show you how." },
  { en: "Beside", ru: "рядом с", example: "She sat beside me." },
  { en: "Property", ru: "собственность; имущество", example: "This is private property." },
  { en: "Inspire", ru: "вдохновлять", example: "Her story inspired me to write a book." },
  { en: "I am counting on you", ru: "Я рассчитываю на тебя", example: "I am counting on you to help me." },
  { en: "At all costs", ru: "любой ценой", example: "We must finish this project at all costs." },
  { en: "Blow something", ru: "взрывать; дуть (на что-то)", example: "The wind blew the hat off my head." },
  { en: "To make good", ru: "исправиться; выполнить обещанное", example: "He made good on his promise." },
  { en: "Shift", ru: "сдвиг; смена", example: "I work the night shift." },
  { en: "You put it back on", ru: "Ты надеваешь это обратно", example: "You put it back on the shelf." },
  { en: "Make sure", ru: "убедиться", example: "Make sure you lock the door." },
  { en: "Ensure", ru: "гарантировать; обеспечивать", example: "Please ensure that all lights are off." }
];
