const words = [
  { en: "Mayhem", ru: "хаос, беспорядок", example: "There was total mayhem in the streets." },
  { en: "Front-row seats", ru: "места в первом ряду", example: "We got front-row seats at the concert." },
  { en: "Destruction", ru: "разрушение", example: "The storm caused massive destruction." },
  { en: "Saying", ru: "пословица, поговорка", example: "As the saying goes, time heals all wounds." },
  { en: "I wonder how", ru: "Интересно, как", example: "I wonder how they did it." },
  { en: "Demolition", ru: "снос, разбор", example: "The demolition of the old building is scheduled for Monday." },
  { en: "Vowels", ru: "гласные", example: "A, E, I, O, U are vowels." },
  { en: "Say a few words", ru: "сказать пару слов", example: "Would you like to say a few words at the ceremony?" },
  { en: "To mark the occasion", ru: "отметить событие", example: "We opened a bottle of wine to mark the occasion." },
  { en: "People are asking me if I know something", ru: "Люди спрашивают меня, знаю ли я что-то", example: "People are asking me if I know something about the accident." },
  { en: "Hidden", ru: "скрытый, спрятанный", example: "There was a hidden message in the letter." },
  { en: "Testicular", ru: "яичковый", example: "Testicular cancer is treatable if caught early." },
  { en: "Support", ru: "поддержка", example: "Thank you for your support." },
  { en: "Realize", ru: "осознавать, понимать", example: "I didn't realize how late it was." },
  { en: "Have something to do with", ru: "иметь отношение к", example: "Does this have something to do with the project?" },
  { en: "comb", ru: "расчёска", example: "She used a comb to fix her hair." },
  { en: "The tomb", ru: "могила, гробница", example: "They discovered an ancient tomb in Egypt." },
  { en: "Accomplished", ru: "достигнутый,successful", example: "She is an accomplished pianist." },
  { en: "cinder", ru: " уголь, зола", example: "The cinder from the fire was still warm." },
  { en: "Smoldering rubble", ru: " тлеющие обломки", example: "The building was reduced to smoldering rubble." },
  { en: "Smolder", ru: "тлеть, дымиться", example: "The fire continued to smolder for hours." },
  { en: "Reduce", ru: "уменьшать, снижать", example: "We need to reduce our expenses." },
  { en: "Wrap", ru: "заворачивать, обёртка", example: "Help me wrap this gift." },
  { en: "Influence", ru: "влияние", example: "Parents have a big influence on their children." },
  { en: "Impact", ru: "влияние, удар", example: "The impact of the new policy was significant." },
  { en: "Enormous", ru: "огромный", example: "The elephant was enormous." },
  { en: "Wound", ru: "рана", example: "The wound on his arm was deep." },
  { en: "Drain the fluid", ru: "слить жидкость", example: "The doctor had to drain the fluid from his knee." },
  { en: "Upped", ru: "повысил, увеличил", example: "They upped the price by 10 percent." },
  { en: "Oestrogen", ru: "эстроген", example: "Oestrogen levels change during the menstrual cycle." },
  { en: "Testosterone", ru: "тестостерон", example: "Testosterone is a male hormone." },
  { en: "Remove", ru: "удалять, убирать", example: "Please remove your shoes before entering." },
  { en: "Slopy", ru: "кривой, неровный", example: "The handwriting was slopy and hard to read." },
  { en: "Moose", ru: "лось", example: "We saw a moose in the forest." },
  { en: "Slobber", ru: "слюни, пускать слюни", example: "The dog slobbered all over the couch." },
  { en: "fold", ru: "складывать, сгибать", example: "Fold the paper in half." },
  { en: "Ultimate", ru: "конечный, лучший", example: "This is the ultimate guide to cooking." },
  { en: "Return to the fold", ru: "вернуться в стаю, вернуться в круг", example: "He finally returned to the fold after years away." },
  { en: "Crook", ru: "мошенник, изгиб", example: "The crook was arrested by the police." },
  { en: "Draft", ru: "черновик, сквозняк", example: "I need to write a draft of the report." },
  { en: "Feel a draft", ru: "чувствовать сквозняк", example: "I feel a draft from that window." },
  { en: "Cowl", ru: "капюшон, колпак", example: "He pulled his cowl over his head." },
  { en: "Chimp", ru: "шимпанзе", example: "The chimp was eating a banana." },
  { en: "Rumor", ru: "слух", example: "There's a rumor that the company is closing." },
  { en: "Gem", ru: "драгоценный камень", example: "The ring had a beautiful gem." },
  { en: "To attend to", ru: "присматривать за, обрабатывать", example: "I need to attend to some urgent matters." },
  { en: "Stuffing", ru: "начинка, набивка", example: "The turkey was filled with delicious stuffing." },
  { en: "Gravy", ru: "соус, подливка", example: "Pour the gravy over the mashed potatoes." },
  { en: "Monk", ru: "монах", example: "The monk lived alone in the monastery." },
  { en: "Grief", ru: "горе, печаль", example: "She was overcome with grief after the loss." },
  { en: "To suffer", ru: "страдать", example: "He suffered from a severe headache." },
  { en: "Torture", ru: "пытка, мука", example: "Waiting for the results was torture." },
  { en: "Thief", ru: "вор", example: "The thief stole her wallet." },
  { en: "Sneaky pickpocket", ru: "хитрый карманник", example: "A sneaky pickpocket stole his phone on the bus." },
  { en: "Sneaky", ru: "хитрый, скрытный", example: "That was a sneaky trick." },
  { en: "Keep away from me", ru: "держись от меня подальше", example: "Keep away from me, I'm contagious!" },
  { en: "Clumsy", ru: "неуклюжий", example: "He's so clumsy, he dropped the vase." },
  { en: "Beggar", ru: "нищий, попрошайка", example: "The beggar asked for some money." },
  { en: "Beg", ru: "просить, выпрашивать", example: "I beg your pardon?" },
  { en: "To be up to something", ru: "что-то замышлять", example: "I think you're up to something." },
  { en: "Junkfood", ru: "фастфуд", example: "Too much junkfood is bad for your health." },
  { en: "Junk", ru: "мусор, хлам", example: "We need to clear out all this junk." },
  { en: "Bargain", ru: "сделка, выгодная покупка", example: "This shirt was a real bargain." },
  { en: "Priceless", ru: "бесценный", example: "The look on her face was priceless." },
  { en: "Worthless", ru: "бесполезный, ничего не стоящий", example: "That old phone is worthless now." },
  { en: "Worth", ru: "стоимость, ценность", example: "What is this painting worth?" },
  { en: "Riddle", ru: "загадка", example: "Can you solve this riddle?" },
  { en: "Stir", ru: "помешивать, взбаламутить", example: "Stir the soup before serving." },
  { en: "Terrain", ru: "местность, рельеф", example: "The terrain was rough and rocky." },
  { en: "Busload", ru: "автобус (загрузка)", example: "A busload of tourists arrived at the museum." },
  { en: "Molest", ru: "преследовать, домогаться", example: "He was arrested for molesting a minor." }
];
